### ISSUE TITLE
Let's implement a skeleton of the project

### ISSUE THREAD

**Issue by aivinog1** [aivinog1/test-cardpay#1]
This project must be a Spring Boot CLI application, builds with maven, and be an uber jar. Also, the CI must be set up.

**Comment by 0pdd** [comment]
@aivinog1 5 puzzles [#10](https://github.com/aivinog1/test-cardpay/issues/10), [#6](https://github.com/aivinog1/test-cardpay/issues/6), [#7](https://github.com/aivinog1/test-cardpay/issues/7), [#8](https://github.com/aivinog1/test-cardpay/issues/8), [#9](https://github.com/aivinog1/test-cardpay/issues/9) are still not solved.

**Comment by aivinog1** [comment]
Todos was created, let's close this.

**Comment by 0pdd** [comment]
@aivinog1 4 puzzles [#10](https://github.com/aivinog1/test-cardpay/issues/10), [#7](https://github.com/aivinog1/test-cardpay/issues/7), [#8](https://github.com/aivinog1/test-cardpay/issues/8), [#9](https://github.com/aivinog1/test-cardpay/issues/9) are still not solved; solved: [#6](https://github.com/aivinog1/test-cardpay/issues/6).

**Comment by 0pdd** [comment]
@aivinog1 3 puzzles [#7](https://github.com/aivinog1/test-cardpay/issues/7), [#8](https://github.com/aivinog1/test-cardpay/issues/8), [#9](https://github.com/aivinog1/test-cardpay/issues/9) are still not solved; solved: [#10](https://github.com/aivinog1/test-cardpay/issues/10), [#6](https://github.com/aivinog1/test-cardpay/issues/6).

**Comment by 0pdd** [comment]
@aivinog1 3 puzzles [#44](https://github.com/aivinog1/test-cardpay/issues/44), [#7](https://github.com/aivinog1/test-cardpay/issues/7), [#8](https://github.com/aivinog1/test-cardpay/issues/8) are still not solved; solved: [#10](https://github.com/aivinog1/test-cardpay/issues/10), [#6](https://github.com/aivinog1/test-cardpay/issues/6), [#9](https://github.com/aivinog1/test-cardpay/issues/9).

**Comment by 0pdd** [comment]
@aivinog1 2 puzzles [#44](https://github.com/aivinog1/test-cardpay/issues/44), [#7](https://github.com/aivinog1/test-cardpay/issues/7) are still not solved; solved: [#10](https://github.com/aivinog1/test-cardpay/issues/10), [#6](https://github.com/aivinog1/test-cardpay/issues/6), [#8](https://github.com/aivinog1/test-cardpay/issues/8), [#9](https://github.com/aivinog1/test-cardpay/issues/9).
