### ISSUE TITLE
Let's implement CSV parsing

### ISSUE THREAD

**Issue by aivinog1** [aivinog1/test-cardpay#2]
This application should parse CSV files to some structure. As requirement parsing should be parallel.

**Comment by 0pdd** [comment]
@aivinog1 3 puzzles [#51](https://github.com/aivinog1/test-cardpay/issues/51), [#52](https://github.com/aivinog1/test-cardpay/issues/52), [#53](https://github.com/aivinog1/test-cardpay/issues/53) are still not solved.

**Comment by aivinog1** [comment]
Issues were created, let's close this.
