### ISSUE TITLE
Create and provide executor for excecution service.

### ISSUE THREAD

**Issue by aivinog1** [aivinog1/test-cardpay#26]
We need a separate non-default executor for executing async tasks.

**Comment by 0pdd** [comment]
@aivinog1 the puzzle [#39](https://github.com/aivinog1/test-cardpay/issues/39) is still not solved.

**Comment by aivinog1** [comment]
TODO has created, let's close this.

**Comment by 0pdd** [comment]
@aivinog1 the only puzzle [#39](https://github.com/aivinog1/test-cardpay/issues/39) is solved here.
