### ISSUE TITLE
Let's implement parsing JSON

### ISSUE THREAD

**Issue by aivinog1** [aivinog1/test-cardpay#3]
Similar to #2, we should parse a JSON to some structure. As requirement parsing should be parallel.

**Comment by 0pdd** [comment]
@aivinog1 6 puzzles [#14](https://github.com/aivinog1/test-cardpay/issues/14), [#15](https://github.com/aivinog1/test-cardpay/issues/15), [#16](https://github.com/aivinog1/test-cardpay/issues/16), [#17](https://github.com/aivinog1/test-cardpay/issues/17), [#18](https://github.com/aivinog1/test-cardpay/issues/18), [#19](https://github.com/aivinog1/test-cardpay/issues/19) are still not solved.

**Comment by aivinog1** [comment]
Let's close this. Todo tasks were created.

**Comment by 0pdd** [comment]
@aivinog1 7 puzzles [#15](https://github.com/aivinog1/test-cardpay/issues/15), [#16](https://github.com/aivinog1/test-cardpay/issues/16), [#17](https://github.com/aivinog1/test-cardpay/issues/17), [#18](https://github.com/aivinog1/test-cardpay/issues/18), [#19](https://github.com/aivinog1/test-cardpay/issues/19), [#23](https://github.com/aivinog1/test-cardpay/issues/23), [#24](https://github.com/aivinog1/test-cardpay/issues/24) are still not solved; solved: [#14](https://github.com/aivinog1/test-cardpay/issues/14).

**Comment by 0pdd** [comment]
@aivinog1 6 puzzles [#15](https://github.com/aivinog1/test-cardpay/issues/15), [#16](https://github.com/aivinog1/test-cardpay/issues/16), [#18](https://github.com/aivinog1/test-cardpay/issues/18), [#19](https://github.com/aivinog1/test-cardpay/issues/19), [#23](https://github.com/aivinog1/test-cardpay/issues/23), [#24](https://github.com/aivinog1/test-cardpay/issues/24) are still not solved; solved: [#14](https://github.com/aivinog1/test-cardpay/issues/14), [#17](https://github.com/aivinog1/test-cardpay/issues/17).

**Comment by 0pdd** [comment]
@aivinog1 13 puzzles [#15](https://github.com/aivinog1/test-cardpay/issues/15), [#16](https://github.com/aivinog1/test-cardpay/issues/16), [#19](https://github.com/aivinog1/test-cardpay/issues/19), [#23](https://github.com/aivinog1/test-cardpay/issues/23), [#24](https://github.com/aivinog1/test-cardpay/issues/24), [#28](https://github.com/aivinog1/test-cardpay/issues/28), [#29](https://github.com/aivinog1/test-cardpay/issues/29), [#30](https://github.com/aivinog1/test-cardpay/issues/30), [#31](https://github.com/aivinog1/test-cardpay/issues/31), [#32](https://github.com/aivinog1/test-cardpay/issues/32), [#33](https://github.com/aivinog1/test-cardpay/issues/33), [#34](https://github.com/aivinog1/test-cardpay/issues/34), [#35](https://github.com/aivinog1/test-cardpay/issues/35) are still not solved; solved: [#14](https://github.com/aivinog1/test-cardpay/issues/14), [#17](https://github.com/aivinog1/test-cardpay/issues/17), [#18](https://github.com/aivinog1/test-cardpay/issues/18).

**Comment by 0pdd** [comment]
@aivinog1 13 puzzles [#15](https://github.com/aivinog1/test-cardpay/issues/15), [#16](https://github.com/aivinog1/test-cardpay/issues/16), [#19](https://github.com/aivinog1/test-cardpay/issues/19), [#23](https://github.com/aivinog1/test-cardpay/issues/23), [#24](https://github.com/aivinog1/test-cardpay/issues/24), [#28](https://github.com/aivinog1/test-cardpay/issues/28), [#29](https://github.com/aivinog1/test-cardpay/issues/29), [#31](https://github.com/aivinog1/test-cardpay/issues/31), [#32](https://github.com/aivinog1/test-cardpay/issues/32), [#33](https://github.com/aivinog1/test-cardpay/issues/33), [#34](https://github.com/aivinog1/test-cardpay/issues/34), [#35](https://github.com/aivinog1/test-cardpay/issues/35), [#41](https://github.com/aivinog1/test-cardpay/issues/41) are still not solved; solved: [#14](https://github.com/aivinog1/test-cardpay/issues/14), [#17](https://github.com/aivinog1/test-cardpay/issues/17), [#18](https://github.com/aivinog1/test-cardpay/issues/18), [#30](https://github.com/aivinog1/test-cardpay/issues/30).

**Comment by 0pdd** [comment]
@aivinog1 12 puzzles [#15](https://github.com/aivinog1/test-cardpay/issues/15), [#16](https://github.com/aivinog1/test-cardpay/issues/16), [#23](https://github.com/aivinog1/test-cardpay/issues/23), [#24](https://github.com/aivinog1/test-cardpay/issues/24), [#28](https://github.com/aivinog1/test-cardpay/issues/28), [#29](https://github.com/aivinog1/test-cardpay/issues/29), [#31](https://github.com/aivinog1/test-cardpay/issues/31), [#32](https://github.com/aivinog1/test-cardpay/issues/32), [#33](https://github.com/aivinog1/test-cardpay/issues/33), [#34](https://github.com/aivinog1/test-cardpay/issues/34), [#35](https://github.com/aivinog1/test-cardpay/issues/35), [#41](https://github.com/aivinog1/test-cardpay/issues/41) are still not solved; solved: [#14](https://github.com/aivinog1/test-cardpay/issues/14), [#17](https://github.com/aivinog1/test-cardpay/issues/17), [#18](https://github.com/aivinog1/test-cardpay/issues/18), [#19](https://github.com/aivinog1/test-cardpay/issues/19), [#30](https://github.com/aivinog1/test-cardpay/issues/30).

**Comment by 0pdd** [comment]
@aivinog1 13 puzzles [#15](https://github.com/aivinog1/test-cardpay/issues/15), [#16](https://github.com/aivinog1/test-cardpay/issues/16), [#23](https://github.com/aivinog1/test-cardpay/issues/23), [#24](https://github.com/aivinog1/test-cardpay/issues/24), [#28](https://github.com/aivinog1/test-cardpay/issues/28), [#31](https://github.com/aivinog1/test-cardpay/issues/31), [#32](https://github.com/aivinog1/test-cardpay/issues/32), [#33](https://github.com/aivinog1/test-cardpay/issues/33), [#34](https://github.com/aivinog1/test-cardpay/issues/34), [#35](https://github.com/aivinog1/test-cardpay/issues/35), [#41](https://github.com/aivinog1/test-cardpay/issues/41), [#47](https://github.com/aivinog1/test-cardpay/issues/47), [#48](https://github.com/aivinog1/test-cardpay/issues/48) are still not solved; solved: [#14](https://github.com/aivinog1/test-cardpay/issues/14), [#17](https://github.com/aivinog1/test-cardpay/issues/17), [#18](https://github.com/aivinog1/test-cardpay/issues/18), [#19](https://github.com/aivinog1/test-cardpay/issues/19), [#29](https://github.com/aivinog1/test-cardpay/issues/29), [#30](https://github.com/aivinog1/test-cardpay/issues/30).

**Comment by 0pdd** [comment]
@aivinog1 12 puzzles [#15](https://github.com/aivinog1/test-cardpay/issues/15), [#16](https://github.com/aivinog1/test-cardpay/issues/16), [#23](https://github.com/aivinog1/test-cardpay/issues/23), [#24](https://github.com/aivinog1/test-cardpay/issues/24), [#28](https://github.com/aivinog1/test-cardpay/issues/28), [#31](https://github.com/aivinog1/test-cardpay/issues/31), [#32](https://github.com/aivinog1/test-cardpay/issues/32), [#33](https://github.com/aivinog1/test-cardpay/issues/33), [#34](https://github.com/aivinog1/test-cardpay/issues/34), [#35](https://github.com/aivinog1/test-cardpay/issues/35), [#47](https://github.com/aivinog1/test-cardpay/issues/47), [#48](https://github.com/aivinog1/test-cardpay/issues/48) are still not solved; solved: [#14](https://github.com/aivinog1/test-cardpay/issues/14), [#17](https://github.com/aivinog1/test-cardpay/issues/17), [#18](https://github.com/aivinog1/test-cardpay/issues/18), [#19](https://github.com/aivinog1/test-cardpay/issues/19), [#29](https://github.com/aivinog1/test-cardpay/issues/29), [#30](https://github.com/aivinog1/test-cardpay/issues/30), [#41](https://github.com/aivinog1/test-cardpay/issues/41).
