### ISSUE TITLE
Let's implement converting and output

### ISSUE THREAD

**Issue by aivinog1** [aivinog1/test-cardpay#4]
After #2 and #3, we should return special JSON and such converting must be parallel.

**Comment by 0pdd** [comment]
@aivinog1 the puzzle [#12](https://github.com/aivinog1/test-cardpay/issues/12) is still not solved.

**Comment by aivinog1** [comment]
Let's close this.

**Comment by 0pdd** [comment]
@aivinog1 the only puzzle [#12](https://github.com/aivinog1/test-cardpay/issues/12) is solved here.
